version: '3'
services:
  www:
    container_name: mfb_www
    build: 
      context: ./www
      dockerfile: Dockerfile.dev
    volumes:
      - ./www:/var/www/public
    depends_on:
      - nginx_api
  nginx_api:
    container_name: mfb_nginx_www
    build: 
      context: ./www
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8000:80
  postgres:
    container_name: mfb_postgres
    image: postgres:15.4
    environment:
      POSTGRES_USER: mfb_user
      POSTGRES_PASSWORD: mfb_pass
      POSTGRES_DB: mfb_db
    ports:
      - 5432:5432
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - ./init:/init
      - ./init/tables.sql:/docker-entrypoint-initdb.d/tables.sql

volumes:
  postgres_db_data:
